In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.io import loadmat
!pip install numpy pandas matplotlib

Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (1.26.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (3.10.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (3.2.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

READ PKL FILE S2

In [ ]:
import pickle

# Load the .pkl file using the 'latin1' encoding
with open("/content/drive/MyDrive/FDA PROJECT 2/S2/S2.pkl", "rb") as file:
    data = pickle.load(file, encoding='latin1')  # Specify 'latin1' encoding

print(data)  # Display the contents

{'signal': {'chest': {'ACC': array([[ 0.95539999, -0.222     , -0.55799997],
       [ 0.92579997, -0.2216    , -0.55379999],
       [ 0.90820003, -0.21960002, -0.53920001],
       ...,
       [ 0.87179995, -0.12379998, -0.30419999],
       [ 0.87300003, -0.12339997, -0.30260003],
       [ 0.87020004, -0.12199998, -0.30220002]]), 'ECG': array([[ 0.02142334],
       [ 0.02032471],
       [ 0.01652527],
       ...,
       [-0.00544739],
       [ 0.00013733],
       [ 0.0040741 ]]), 'EMG': array([[-0.00444031],
       [ 0.00434875],
       [ 0.00517273],
       ...,
       [-0.01716614],
       [-0.02897644],
       [-0.02357483]]), 'EDA': array([[5.25054932],
       [5.26733398],
       [5.24330139],
       ...,
       [0.36048889],
       [0.36582947],
       [0.365448  ]]), 'Temp': array([[30.120758],
       [30.129517],
       [30.138214],
       ...,
       [31.459229],
       [31.484283],
       [31.456268]], dtype=float32), 'Resp': array([[-1.14898682],
       [-1.12457275],
       [-1.15203857],
       ...,
       [-1.10321045],
       [-1.08642578],
       [-1.09710693]])}, 'wrist': {'ACC': array([[ 62., -21., 107.],
       [ 66.,  13.,  53.],
       [ 41.,   9.,  15.],
       ...,
       [ 41.,  25.,  11.],
       [ 39.,  27.,  22.],
       [ 56.,  26.,  10.]]), 'BVP': array([[-59.37],
       [-53.42],
       [-44.4 ],
       ...,
       [ 18.26],
       [ 18.68],
       [ 19.71]]), 'EDA': array([[1.138257],
       [1.125444],
       [1.011405],
       ...,
       [0.059208],
       [0.073303],
       [0.045113]]), 'TEMP': array([[35.41],
       [35.41],
       [35.41],
       ...,
       [34.23],
       [34.23],
       [34.23]])}}, 'label': array([0, 0, 0, ..., 0, 0, 0], dtype=int32), 'subject': 'S2'}

CONVERT TO DATAFRAME FOR SUBJECT S2

In [ ]:
import pickle
import pandas as pd

# Load the .pkl file using the 'latin1' encoding
with open("/content/drive/MyDrive/FDA PROJECT 2/S2/S2.pkl", "rb") as file:
    data = pickle.load(file, encoding='latin1')  # Specify 'latin1' encoding

#print(data)  # Display the contents
S2 = data # Assign the loaded data to S2
data4 = S2['signal']['chest']['ACC']
dfS2 = pd.DataFrame(data = data4, columns = ['acc_x', 'acc_y', 'acc_z'])

def add_multiple_columns(dfS2, column_names, S2, S2_column):
    for col in column_names:
        dfS2[col] = S2['signal']['chest'][col]
    return dfS2

column_names = ['ECG', 'EMG', 'EDA', 'Temp', 'Resp']
dfS2 = add_multiple_columns(dfS2, column_names, S2, 'ECG')
dfS2['State'] = S2.get('label')
dfS2['Subject'] = S2.get('subject')
dfS2

,acc_x,acc_y,acc_z,ECG,EMG,EDA,Temp,Resp,State,Subject
0,0.9554,-0.2220,-0.5580,0.021423,-0.004440,5.250549,30.120758,-1.148987,0,S2
1,0.9258,-0.2216,-0.5538,0.020325,0.004349,5.267334,30.129517,-1.124573,0,S2
2,0.9082,-0.2196,-0.5392,0.016525,0.005173,5.243301,30.138214,-1.152039,0,S2
3,0.8974,-0.2102,-0.5122,0.016708,0.007187,5.249405,30.129517,-1.158142,0,S2
4,0.8882,-0.2036,-0.4824,0.011673,-0.015152,5.286407,30.130951,-1.161194,0,S2
...,...,...,...,...,...,...,...,...,...,...
4255295,0.8750,-0.1234,-0.2974,-0.013138,0.020370,0.400162,31.457733,-1.063538,0,S2
4255296,0.8750,-0.1262,-0.2988,-0.010345,0.019592,0.355911,31.476898,-1.106262,0,S2
4255297,0.8718,-0.1238,-0.3042,-0.005447,-0.017166,0.360489,31.459229,-1.103210,0,S2
4255298,0.8730,-0.1234,-0.3026,0.000137,-0.028976,0.365829,31.484283,-1.086426,0,S2
4255299,0.8702,-0.1220,-0.3022,0.004074,-0.023575,0.365448,31.456268,-1.097107,0,S2

READ PKL FILE S3

In [3]:
import pickle

# Load the .pkl file using the 'latin1' encoding
with open("/content/drive/MyDrive/FDA PROJECT 2/S3/S3.pkl", "rb") as file:
    data = pickle.load(file, encoding='latin1')  # Specify 'latin1' encoding

print(data)  # Display the contents

{'signal': {'chest': {'ACC': array([[ 7.20000029e-01, -1.38199985e-01,  3.19339991e+00],
       [ 5.68799973e-01, -2.28600025e-01,  3.18219995e+00],
       [ 3.99799943e-01, -3.13199997e-01,  2.94499993e+00],
       ...,
       [ 9.01800036e-01,  5.85999489e-02, -7.79998302e-03],
       [ 9.07400012e-01,  7.62000084e-02,  2.59995461e-03],
       [ 9.68199968e-01,  1.83400035e-01,  1.79999948e-01]]), 'ECG': array([[-0.75663757],
       [-0.70820618],
       [-0.67396545],
       ...,
       [-0.24847412],
       [-0.18598938],
       [-0.14176941]]), 'EMG': array([[ 0.00595093],
       [-0.0385437 ],
       [-0.04943848],
       ...,
       [-0.11604309],
       [-0.11082458],
       [-0.06486511]]), 'EDA': array([[7.98835754],
       [7.98225403],
       [7.98339844],
       ...,
       [7.53211975],
       [7.53059387],
       [7.5340271 ]]), 'Temp': array([[31.499023],
       [31.501953],
       [31.521149],
       ...,
       [33.228973],
       [33.215393],
       [33.242523]], dtype=float32), 'Resp': array([[2.20489502],
       [2.18048096],
       [2.16674805],
       ...,
       [1.34429932],
       [1.34124756],
       [1.34429932]])}, 'wrist': {'ACC': array([[-128.,  127.,  127.],
       [ -41.,   49.,   76.],
       [  -3.,   14.,   14.],
       ...,
       [ -55.,  -34.,   12.],
       [ -54.,  -34.,   11.],
       [ -54.,  -34.,   11.]]), 'BVP': array([[16.49],
       [15.8 ],
       [14.58],
       ...,
       [ 4.98],
       [ 4.74],
       [ 4.44]]), 'EDA': array([[2.248749],
       [2.710001],
       [2.554969],
       ...,
       [0.301362],
       [0.301362],
       [0.301362]]), 'TEMP': array([[31.73],
       [31.73],
       [31.73],
       ...,
       [30.81],
       [30.83],
       [30.83]])}}, 'label': array([0, 0, 0, ..., 0, 0, 0], dtype=int32), 'subject': 'S3'}

CONVERT TO DATAFRAME FOR SUBJECT S3

In [5]:
import pickle
import pandas as pd

# Load the .pkl file using the 'latin1' encoding
with open("/content/drive/MyDrive/FDA PROJECT 2/S3/S3.pkl", "rb") as file:
    data = pickle.load(file, encoding='latin1')  # Specify 'latin1' encoding

#print(data)  # Display the contents
S3 = data # Assign the loaded data to S3
data4 = S3['signal']['chest']['ACC']
dfS3 = pd.DataFrame(data = data4, columns = ['acc_x', 'acc_y', 'acc_z'])

def add_multiple_columns(dfS3, column_names, S3, S3_column):
    for col in column_names:
        dfS3[col] = S3['signal']['chest'][col]
    return dfS3

column_names = ['ECG', 'EMG', 'EDA', 'Temp', 'Resp']
dfS3 = add_multiple_columns(dfS3, column_names, S3, 'ECG')
dfS3['State'] = S3.get('label')
dfS3['Subject'] = S3.get('subject')
dfS3

,acc_x,acc_y,acc_z,ECG,EMG,EDA,Temp,Resp,State,Subject
0,0.7200,-0.1382,3.1934,-0.756638,0.005951,7.988358,31.499023,2.204895,0,S3
1,0.5688,-0.2286,3.1822,-0.708206,-0.038544,7.982254,31.501953,2.180481,0,S3
2,0.3998,-0.3132,2.9450,-0.673965,-0.049438,7.983398,31.521149,2.166748,0,S3
3,0.2454,-0.3838,2.4716,-0.535721,-0.014465,7.981873,31.510834,2.191162,0,S3
4,0.0938,-0.4466,1.8758,-0.321808,0.027603,7.978821,31.516724,2.183533,0,S3
...,...,...,...,...,...,...,...,...,...,...
4545095,0.9150,0.0514,0.0192,-0.345840,0.034149,7.535934,33.213867,1.371765,0,S3
4545096,0.9086,0.0554,0.0006,-0.304916,-0.039139,7.533646,33.225922,1.356506,0,S3
4545097,0.9018,0.0586,-0.0078,-0.248474,-0.116043,7.532120,33.228973,1.344299,0,S3
4545098,0.9074,0.0762,0.0026,-0.185989,-0.110825,7.530594,33.215393,1.341248,0,S3
4545099,0.9682,0.1834,0.1800,-0.141769,-0.064865,7.534027,33.242523,1.344299,0,S3

READ PKL FILE S4

In [ ]:
import pickle

# Load the .pkl file using the 'latin1' encoding
with open("/content/drive/MyDrive/FDA PROJECT 2/S4/S4.pkl", "rb") as file:
    data = pickle.load(file, encoding='latin1')  # Specify 'latin1' encoding

print(data)  # Display the contents

{'signal': {'chest': {'ACC': array([[ 1.55539989, -0.07840002,  1.36240005],
       [ 1.51300001, -0.10699999,  1.45860004],
       [ 1.4460001 , -0.10420001,  1.06040001],
       ...,
       [ 0.89020002, -0.079     , -0.23000002],
       [ 0.8908    , -0.07980001, -0.22659999],
       [ 0.88940001, -0.0794    , -0.22780001]]), 'ECG': array([[-1.40538025],
       [-1.3996582 ],
       [-1.39338684],
       ...,
       [ 0.11128235],
       [ 0.12547302],
       [ 0.13499451]]), 'EMG': array([[ 0.04417419],
       [ 0.01547241],
       [-0.03204346],
       ...,
       [ 0.00567627],
       [ 0.01625061],
       [-0.00013733]]), 'EDA': array([[1.09634399],
       [1.09443665],
       [1.09405518],
       ...,
       [2.48260498],
       [2.49443054],
       [2.49404907]]), 'Temp': array([[32.506256],
       [32.49878 ],
       [32.50177 ],
       ...,
       [33.630707],
       [33.633728],
       [33.62918 ]], dtype=float32), 'Resp': array([[2.83660889],
       [2.83966064],
       [2.83813477],
       ...,
       [2.58178711],
       [2.57110596],
       [2.56195068]])}, 'wrist': {'ACC': array([[-128.,  122.,   88.],
       [ -31.,  -34.,   77.],
       [ -61.,    4.,   62.],
       ...,
       [   5.,  -29.,   55.],
       [   6.,  -29.,   56.],
       [   6.,  -28.,   56.]]), 'BVP': array([[  -3.69],
       [  -5.53],
       [  -7.82],
       ...,
       [-102.58],
       [-105.06],
       [-106.6 ]]), 'EDA': array([[0.169117],
       [0.164001],
       [0.167838],
       ...,
       [0.139696],
       [0.138417],
       [0.139696]]), 'TEMP': array([[32.53],
       [32.53],
       [32.53],
       ...,
       [31.37],
       [31.37],
       [31.37]])}}, 'label': array([0, 0, 0, ..., 0, 0, 0], dtype=int32), 'subject': 'S4'}

CONVERT TO DATAFRAME FOR SUBJECT S4

In [ ]:
import pickle
import pandas as pd

# Load the .pkl file using the 'latin1' encoding
with open("/content/drive/MyDrive/FDA PROJECT 2/S4/S4.pkl", "rb") as file:
    data = pickle.load(file, encoding='latin1')  # Specify 'latin1' encoding

#print(data)  # Display the contents
S4 = data # Assign the loaded data to S4
data4 = S4['signal']['chest']['ACC']
dfS4 = pd.DataFrame(data = data4, columns = ['acc_x', 'acc_y', 'acc_z'])

def add_multiple_columns(dfS4, column_names, S4, S4_column):
    for col in column_names:
        dfS4[col] = S4['signal']['chest'][col]
    return dfS4

column_names = ['ECG', 'EMG', 'EDA', 'Temp', 'Resp']
dfS4 = add_multiple_columns(dfS4, column_names, S4, 'ECG')
dfS4['State'] = S4.get('label')
dfS4['Subject'] = S4.get('subject')
dfS4

,acc_x,acc_y,acc_z,ECG,EMG,EDA,Temp,Resp,State,Subject
0,1.5554,-0.0784,1.3624,-1.405380,0.044174,1.096344,32.506256,2.836609,0,S4
1,1.5130,-0.1070,1.4586,-1.399658,0.015472,1.094437,32.498779,2.839661,0,S4
2,1.4460,-0.1042,1.0604,-1.393387,-0.032043,1.094055,32.501770,2.838135,0,S4
3,1.3382,-0.0622,0.4234,-1.387436,-0.003799,1.094818,32.491302,2.839661,0,S4
4,1.1958,-0.0306,-0.0164,-1.381165,0.020370,1.092911,32.501770,2.882385,0,S4
...,...,...,...,...,...,...,...,...,...,...
4496095,0.8926,-0.0810,-0.2290,0.082443,0.008743,2.483749,33.650391,2.578735,0,S4
4496096,0.8944,-0.0824,-0.2276,0.093796,-0.024673,2.480698,33.650391,1.963806,0,S4
4496097,0.8902,-0.0790,-0.2300,0.111282,0.005676,2.482605,33.630707,2.581787,0,S4
4496098,0.8908,-0.0798,-0.2266,0.125473,0.016251,2.494431,33.633728,2.571106,0,S4
4496099,0.8894,-0.0794,-0.2278,0.134995,-0.000137,2.494049,33.629181,2.561951,0,S4

READ PKL FILE S5

In [2]:
import pickle

# Load the .pkl file using the 'latin1' encoding
with open("/content/drive/MyDrive/FDA PROJECT 2/S5/S5.pkl", "rb") as file:
    data = pickle.load(file, encoding='latin1')  # Specify 'latin1' encoding

print(data)  # Display the contents

{'signal': {'chest': {'ACC': array([[ 0.86059999,  0.07420003,  0.85699999],
       [ 0.84560001,  0.07799995,  0.85739994],
       [ 0.84099996,  0.08739996,  0.75699997],
       ...,
       [ 0.90960002, -0.05620003, -0.12940001],
       [ 0.9102    , -0.05580002, -0.13260001],
       [ 0.91059995, -0.05680001, -0.13739997]]), 'ECG': array([[-0.27580261],
       [-0.22975159],
       [-0.19528198],
       ...,
       [ 0.01487732],
       [ 0.0292511 ],
       [ 0.03886414]]), 'EMG': array([[ 0.01679993],
       [ 0.01496887],
       [ 0.01533508],
       ...,
       [-0.01368713],
       [-0.00100708],
       [ 0.003479  ]]), 'EDA': array([[ 3.88832092],
       [ 3.91311646],
       [ 3.87306213],
       ...,
       [10.23101807],
       [10.2306366 ],
       [10.2306366 ]]), 'Temp': array([[34.119934],
       [34.142822],
       [34.135193],
       ...,
       [34.949463],
       [34.97107 ],
       [34.940247]], dtype=float32), 'Resp': array([[0.04425049],
       [0.03204346],
       [0.01525879],
       ...,
       [7.05718994],
       [7.09075928],
       [7.07550049]])}, 'wrist': {'ACC': array([[-16., -45., 127.],
       [ 69.,   9., 127.],
       [ 45.,  35., -12.],
       ...,
       [ 45.,  39.,  20.],
       [ 46.,  39.,  20.],
       [ 46.,  39.,  19.]]), 'BVP': array([[-7.25],
       [-8.57],
       [-9.48],
       ...,
       [-4.13],
       [-7.07],
       [-9.88]]), 'EDA': array([[0.547723],
       [0.481218],
       [0.518239],
       ...,
       [0.985122],
       [0.965938],
       [0.955706]]), 'TEMP': array([[34.09],
       [34.09],
       [34.09],
       ...,
       [31.03],
       [31.03],
       [31.01]])}}, 'label': array([0, 0, 0, ..., 0, 0, 0], dtype=int32), 'subject': 'S5'}

CONVERT TO DATAFRAME FOR SUBJECT S5

In [7]:
import pickle
import pandas as pd

# Load the .pkl file using the 'latin1' encoding
with open("/content/drive/MyDrive/FDA PROJECT 2/S5/S5.pkl", "rb") as file:
    data = pickle.load(file, encoding='latin1')  # Specify 'latin1' encoding

#print(data)  # Display the contents
S5 = data # Assign the loaded data to S5
data4 = S5['signal']['chest']['ACC']
dfS5 = pd.DataFrame(data = data4, columns = ['acc_x', 'acc_y', 'acc_z'])

def add_multiple_columns(dfS5, column_names, S5, S5_column):
    for col in column_names:
        dfS5[col] = S5['signal']['chest'][col]
    return dfS5

column_names = ['ECG', 'EMG', 'EDA', 'Temp', 'Resp']
dfS5 = add_multiple_columns(dfS5, column_names, S5, 'ECG')
dfS5['State'] = S5.get('label')
dfS5['Subject'] = S5.get('subject')
dfS5

,acc_x,acc_y,acc_z,ECG,EMG,EDA,Temp,Resp,State,Subject
0,0.8606,0.0742,0.8570,-0.275803,0.016800,3.888321,34.119934,0.044250,0,S5
1,0.8456,0.0780,0.8574,-0.229752,0.014969,3.913116,34.142822,0.032043,0,S5
2,0.8410,0.0874,0.7570,-0.195282,0.015335,3.873062,34.135193,0.015259,0,S5
3,0.8418,0.0986,0.5782,-0.164474,-0.003708,3.883362,34.136749,-0.062561,0,S5
4,0.8554,0.0984,0.3332,-0.134811,0.017624,3.886795,34.118439,0.016785,0,S5
...,...,...,...,...,...,...,...,...,...,...
4380595,0.9086,-0.0578,-0.1242,-0.008240,0.009293,10.231400,34.971069,7.070923,0,S5
4380596,0.9086,-0.0572,-0.1286,-0.000778,-0.004074,10.231018,34.900116,7.044983,0,S5
4380597,0.9096,-0.0562,-0.1294,0.014877,-0.013687,10.231018,34.949463,7.057190,0,S5
4380598,0.9102,-0.0558,-0.1326,0.029251,-0.001007,10.230637,34.971069,7.090759,0,S5
4380599,0.9106,-0.0568,-0.1374,0.038864,0.003479,10.230637,34.940247,7.075500,0,S5

READ PKL FILE S6

In [ ]:
import pickle

# Load the .pkl file using the 'latin1' encoding
with open("/content/drive/MyDrive/FDA PROJECT 2/S6/S6.pkl", "rb") as file:
    data = pickle.load(file, encoding='latin1')  # Specify 'latin1' encoding

print(data)  # Display the contents

{'signal': {'chest': {'ACC': array([[ 0.35099995, -0.19059998,  2.28419995],
       [ 0.44219995, -0.1142    ,  2.22160006],
       [ 0.53219998, -0.0582    ,  1.92420006],
       ...,
       [ 0.87979996, -0.06379998, -0.24019998],
       [ 0.88540006, -0.06620002, -0.24379998],
       [ 0.88380003, -0.06739998, -0.24779999]]), 'ECG': array([[0.03337097],
       [0.03639221],
       [0.04046631],
       ...,
       [1.44621277],
       [1.43962097],
       [1.43284607]]), 'EMG': array([[ 0.05534363],
       [ 0.03877258],
       [ 0.0160675 ],
       ...,
       [-0.01670837],
       [-0.01524353],
       [-0.01441956]]), 'EDA': array([[ 9.85984802],
       [ 9.8613739 ],
       [ 9.86175537],
       ...,
       [11.14959717],
       [11.14578247],
       [11.14692688]]), 'Temp': array([[33.037903],
       [33.04239 ],
       [33.05139 ],
       ...,
       [33.829376],
       [33.815674],
       [33.83542 ]], dtype=float32), 'Resp': array([[ 3.10668945],
       [ 3.11126709],
       [ 3.12652588],
       ...,
       [ 0.45928955],
       [-0.09918213],
       [ 0.4776001 ]])}, 'wrist': {'ACC': array([[112., -19., 127.],
       [ 44.,  18.,  10.],
       [ 52.,  16.,  30.],
       ...,
       [ 38.,  32., -15.],
       [ 35.,  39., -37.],
       [ 48.,  45., -51.]]), 'BVP': array([[  4.26],
       [  3.12],
       [  1.7 ],
       ...,
       [-40.67],
       [-47.72],
       [-53.59]]), 'EDA': array([[2.779563],
       [2.785958],
       [2.761658],
       ...,
       [5.724445],
       [5.670729],
       [5.324135]]), 'TEMP': array([[30.03],
       [30.03],
       [30.03],
       ...,
       [32.61],
       [32.59],
       [32.59]])}}, 'label': array([0, 0, 0, ..., 0, 0, 0], dtype=int32), 'subject': 'S6'}

CONVERT TO DATAFRAME FOR SUBJECT S6

In [ ]:
import pickle
import pandas as pd

# Load the .pkl file using the 'latin1' encoding
with open("/content/drive/MyDrive/FDA PROJECT 2/S6/S6.pkl", "rb") as file:
    data = pickle.load(file, encoding='latin1')  # Specify 'latin1' encoding

#print(data)  # Display the contents
S6 = data # Assign the loaded data to S6
data4 = S6['signal']['chest']['ACC']
dfS6 = pd.DataFrame(data = data4, columns = ['acc_x', 'acc_y', 'acc_z'])

def add_multiple_columns(dfS6, column_names, S6, S6_column):
    for col in column_names:
        dfS6[col] = S6['signal']['chest'][col]
    return dfS6

column_names = ['ECG', 'EMG', 'EDA', 'Temp', 'Resp']
dfS6 = add_multiple_columns(dfS6, column_names, S6, 'ECG')
dfS6['State'] = S6.get('label')
dfS6['Subject'] = S6.get('subject')
dfS6

,acc_x,acc_y,acc_z,ECG,EMG,EDA,Temp,Resp,State,Subject
0,0.3510,-0.1906,2.2842,0.033371,0.055344,9.859848,33.037903,3.106689,0,S6
1,0.4422,-0.1142,2.2216,0.036392,0.038773,9.861374,33.042389,3.111267,0,S6
2,0.5322,-0.0582,1.9242,0.040466,0.016068,9.861755,33.051392,3.126526,0,S6
3,0.6926,-0.0010,1.4022,0.042526,0.055206,9.859848,32.985321,3.147888,0,S6
4,0.9018,0.0450,0.6478,0.046371,0.037308,9.859848,33.034882,3.175354,0,S6
...,...,...,...,...,...,...,...,...,...,...
4949695,0.8808,-0.0614,-0.2410,1.459030,-0.036209,11.148453,33.835419,0.425720,0,S6
4949696,0.8786,-0.0622,-0.2376,1.452438,-0.011078,11.147308,33.832397,0.447083,0,S6
4949697,0.8798,-0.0638,-0.2402,1.446213,-0.016708,11.149597,33.829376,0.459290,0,S6
4949698,0.8854,-0.0662,-0.2438,1.439621,-0.015244,11.145782,33.815674,-0.099182,0,S6
4949699,0.8838,-0.0674,-0.2478,1.432846,-0.014420,11.146927,33.835419,0.477600,0,S6